version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run dist

  release:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Release Application to GitHub
          command: npm run release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
