version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-backend:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Restore and Build Backend
          command: |
            cd CompareExcelAPI
            dotnet restore
            dotnet publish -c Release -r win10-x64 --self-contained false -o ./publish

  build:
    executor:
      name: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:4e:ad:49:2d:56:b3:60:6f:ab:2a:09:bb:c4:4f:82"
      - checkout
      - run:
          name: Build Backend API
          command: |
            cd CompareExcelAPI
            dotnet restore
            dotnet publish -c Release -r win10-x64 --self-contained false -o ./publish
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run dist

  release:
    executor:
      name: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:4e:ad:49:2d:56:b3:60:6f:ab:2a:09:bb:c4:4f:82"
      - checkout
      - run:
          name: Build Backend API
          command: |
            cd CompareExcelAPI
            dotnet restore
            dotnet publish -c Release -r win10-x64 --self-contained false -o ./publish
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Dependencies
          command: npm run build
      - run:
          name: Build React
          command: npm run build:react
      - run:
          name: Build Application
          command: npm run dist
      - run:
          name: Release Application to GitHub
          command: npm run release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-backend
      - build:
          requires:
            - build-backend
          filters:
            branches:
              only: develop
      - release:
          requires:
            - build-backend
          filters:
            branches:
              only: master
