version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-develop:
    executor:
      name: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:4e:ad:49:2d:56:b3:60:6f:ab:2a:09:bb:c4:4f:82"
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run dist

  build-master:
    executor:
      name: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:4e:ad:49:2d:56:b3:60:6f:ab:2a:09:bb:c4:4f:82"
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run dist

  release:
    executor:
      name: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:4e:ad:49:2d:56:b3:60:6f:ab:2a:09:bb:c4:4f:82"
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Release Application to GitHub
          command: npm run release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-develop:
          filters:
            branches:
              only: develop
      - build-master:
          filters:
            branches:
              only: master
      - release:
          requires:
            - build-master
          filters:
            branches:
              only: master
