version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-only:
    executor:
      name: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:4e:ad:49:2d:56:b3:60:6f:ab:2a:09:bb:c4:4f:82"
      - checkout
      - run:
          name: Build Backend API
          command: |
            cd CompareExcelAPI
            dotnet restore
            dotnet publish -c Release -r win10-x64 --self-contained false -o ./publish
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run dist

  build-and-release:
    executor:
      name: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:4e:ad:49:2d:56:b3:60:6f:ab:2a:09:bb:c4:4f:82"
      - checkout
      - run:
          name: Install .NET 6.0 SDK
          command: choco install dotnet-sdk --version 6.0.100
      - run:
          name: Build Backend API
          command: |
            cd CompareExcelAPI
            dotnet restore
            dotnet publish -c Release -r win10-x64 --self-contained false -o ./publish
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Dependencies
          command: npm run build
      - run:
          name: Build React
          command: npm run build:react
      - run:
          name: Build Application
          command: npm run dist
      - run:
          name: Release Application to GitHub
          command: npm run release

workflows:
  version: 2
  build-only:
    jobs:
      - build-only:
          filters:
            branches:
              only: develop
  build-and-release:
    jobs:
      - build-and-release:
          filters:
            branches:
              only: master
